name: Build Analysis Artifact

on:
  push:
    branches:
      - master

env:
  ANALYSIS_VERSION: "3.1"

jobs:
  setup:
    name: Compile Code
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.0-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'
            
      - name: Compile Linux
        run:  mvn compile -Plinux64

      - name: Compile Windows
        run:  mvn compile -Pwin64

      - name: Compile Mac
        run:  mvn compile -e -Pdarwin64

      - name: Convert markdown to html
        run:  grip --export help/commands.md

      - name: Deploy
        run: |
          mvn versions:set -DnewVersion=${ANALYSIS_VERSION}.${GITHUB_RUN_NUMBER} -f deploy.pom.xml
          mvn deploy -f deploy.pom.xml
          mvn clean
