name: Compile Analysis

on:
  pull_request:
    branches:
      - master

env:
  ANALYSIS_VERSION: "3.1"

jobs:
  grammar:
    name: Compile Grammars
    runs-on: ubuntu-latest
    container:
      image: epidata/goldparser:1.0.0

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
    
      - name: Compile Full grammar
        run: goldbuild.sh src/grammar/EpiDataAnalysisGrammar.grm

      - name: Compile OptionList grammar
        run: goldbuild.sh src/grammar/EpiDataAnalysisOptionListGrammar.grm

      - name: Fix git permissiong
        run: git config --global --add safe.directory /__w/analysis/analysis

      - name: Commit grammers
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated grammar files

  compile:
    name: Compile Code
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.0-14
    needs: grammar

    strategy:
      fail-fast: false
      matrix:
        profile: [linux64, win64, darwin64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'
            
      - name: Compile ${{ matrix.profile }}
        run:  mvn compile -P${{ matrix.profile }}

  documentation:
    name: Create Help File
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.0-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert markdown to html
        run:  grip --export help/commands.md

